# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G -Xms2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=8
org.gradle.warning.mode=all
#org.gradle.configuration-cache=true
systemProp.http.socketTimeout=600000
systemProp.http.connectionTimeout=600000
systemProp.https.socketTimeout=600000
systemProp.https.connectionTimeout=600000
systemProp.org.gradle.internal.http.connectionTimeout=2147483647
# ~35 minutes
org.gradle.internal.http.socketTimeout=2147483647
# ~35 minutes
systemProp.org.gradle.internal.repository.max.retries=1



## Environment Properties
modId=everythingjapanese
# The human-readable display name for the mod.
modName=Everything Japanese
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
modLicense=MIT
# The mod version. See https://semver.org/
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
modGroupId=net.Chidoziealways.everythingjapanese
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
modAuthors=Chidoziealways
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
modDescription=My First Mod :) \n It adds everything Japanese. Japanese blocks, items, etc. \n ENJOY! (Forge)
