/*import net.minecraftforge.common.capabilities.ICapabilityProvider
import net.Chidoziealways.everythingjapanese.chakra.Chakra
import net.minecraftforge.common.util.LazyOptional
import net.Chidoziealways.everythingjapanese.chakra.IChakra
import net.minecraftforge.common.util.NonNullSupplier
import net.Chidoziealways.everythingjapanese.capabilities.ModCapabilities
import net.minecraft.nbt.CompoundTag
import net.minecraft.nbt.NbtOps
import net.minecraft.world.entity.animal.Animal
import net.minecraft.world.entity.ai.goal.FloatGoal
import net.minecraft.world.entity.ai.goal.PanicGoal
import net.minecraft.world.entity.ai.goal.BreedGoal
import net.minecraft.world.entity.ai.goal.TemptGoal
import net.minecraft.world.item.ItemStack
import net.Chidoziealways.everythingjapanese.item.ModItems
import net.minecraft.world.entity.ai.goal.FollowParentGoal
import net.minecraft.world.entity.ai.goal.WaterAvoidingRandomStrollGoal
import net.minecraft.world.entity.ai.goal.LookAtPlayerGoal
import net.minecraft.world.entity.ai.goal.RandomLookAroundGoal
import net.minecraft.server.level.ServerLevel
import net.minecraft.world.entity.AgeableMob
import net.Chidoziealways.everythingjapanese.entity.ModEntities
import net.minecraft.world.entity.EntitySpawnReason
import net.minecraft.sounds.SoundEvents
import net.minecraft.world.damagesource.DamageSource
import net.minecraft.world.entity.ai.attributes.AttributeSupplier
import net.minecraftforge.fml.common.Mod.EventBusSubscriber
import net.minecraftforge.eventbus.api.listener.SubscribeEvent
import net.minecraftforge.event.RegisterCommandsEvent
import com.mojang.brigadier.CommandDispatcher
import net.minecraft.commands.CommandSourceStack
import net.minecraft.commands.arguments.EntityArgument
import com.mojang.brigadier.context.CommandContext
import net.Chidoziealways.everythingjapanese.commands.comands.GetChakraCommand
import net.minecraftforge.common.util.NonNullConsumer
import net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider
import net.minecraft.client.renderer.blockentity.BlockEntityRenderer
import net.Chidoziealways.everythingjapanese.entity.custom.PedestalBlockEntity
import com.mojang.blaze3d.vertex.PoseStack
import net.minecraft.client.renderer.MultiBufferSource
import net.minecraft.world.phys.Vec3
import net.minecraft.client.renderer.entity.ItemRenderer
import net.minecraft.client.Minecraft
import net.minecraft.world.item.ItemDisplayContext
import net.minecraft.client.renderer.texture.OverlayTexture
import net.minecraft.core.BlockPos
import net.minecraft.world.level.LightLayer
import net.minecraft.client.renderer.LightTexture
import net.minecraft.world.effect.MobEffectCategory
import net.minecraft.world.effect.MobEffect
import net.minecraft.world.entity.LivingEntity
import net.minecraft.network.syncher.SynchedEntityData
import net.minecraft.world.level.storage.ValueInput
import net.minecraft.world.level.storage.ValueOutput
import net.minecraftforge.registries.DeferredRegister
import net.minecraft.commands.synchronization.ArgumentTypeInfo
import net.minecraftforge.registries.RegistryObject
import net.Chidoziealways.everythingjapanese.commands.argumentTypes.jutsu.JutsuArgument
import net.Chidoziealways.everythingjapanese.commands.ModArgumentTypes
import net.minecraft.commands.synchronization.ArgumentTypeInfos
import net.minecraft.commands.synchronization.SingletonArgumentInfo
import net.minecraft.commands.CommandBuildContext
import net.minecraftforge.eventbus.api.bus.BusGroup
import net.minecraftforge.api.distmarker.OnlyIn
import net.minecraftforge.api.distmarker.Dist
import net.minecraft.data.PackOutput
import net.minecraft.client.data.models.blockstates.BlockModelDefinitionGenerator
import net.minecraft.client.data.models.ItemModelOutput
import net.minecraft.client.data.models.model.ModelInstance
import net.minecraft.client.data.models.BlockModelGenerators
import net.Chidoziealways.everythingjapanese.block.ModBlocks
import net.minecraft.client.data.models.model.TexturedModel
import net.minecraft.client.data.models.blockstates.MultiVariantGenerator
import net.minecraft.client.data.models.blockstates.PropertyDispatch
import net.minecraft.world.level.block.state.properties.BlockStateProperties
import net.minecraft.client.data.models.model.ModelTemplates
import net.minecraft.client.data.models.model.TextureMapping
import net.minecraft.client.data.models.MultiVariant
import net.minecraft.client.data.models.model.ModelLocationUtils
import net.minecraft.client.data.models.ModelProvider.BlockStateGeneratorCollector
import net.minecraft.client.data.models.ModelProvider.ItemInfoCollector
import net.minecraft.client.data.models.ModelProvider.SimpleModelCollector
import net.Chidoziealways.everythingjapanese.datagen.ModModelProvider.MyBlockModelGenerators
import net.minecraft.client.data.models.ItemModelGenerators
import net.Chidoziealways.everythingjapanese.item.ModEquipmentAssets
import net.minecraft.resources.ResourceKey
import net.minecraft.world.item.equipment.EquipmentAsset
import net.minecraft.client.renderer.item.SelectItemModel
import net.minecraft.world.item.equipment.trim.TrimMaterial
import net.Chidoziealways.everythingjapanese.datagen.ModModelProvider.MyItemModelGenerators
import net.minecraft.client.renderer.item.ItemModel
import net.minecraft.client.data.models.model.ItemModelUtils
import net.minecraft.client.color.item.Dye
import net.minecraft.client.renderer.item.properties.select.TrimMaterialProperty
import net.minecraft.world.item.equipment.trim.MaterialAssetGroup
import net.Chidoziealways.everythingjapanese.trim.ModMaterialAssetGroup
import net.Chidoziealways.everythingjapanese.trim.ModTrimMaterials
import net.minecraft.world.item.equipment.trim.TrimMaterials
import net.minecraft.core.HolderLookup
import net.minecraft.core.HolderLookup.RegistryLookup
import net.Chidoziealways.everythingjapanese.jutsu.Jutsu
import net.minecraft.resources.RegistryOps
import net.Chidoziealways.everythingjapanese.commands.argumentTypes.jutsu.JutsuParser
import net.Chidoziealways.everythingjapanese.util.ModRegistries
import com.mojang.brigadier.exceptions.CommandSyntaxException
import net.Chidoziealways.everythingjapanese.commands.argumentTypes.jutsu.JutsuParser.JutsuResult
import net.minecraft.core.component.DataComponentPatch
import net.minecraft.core.component.DataComponentType
import com.mojang.brigadier.suggestion.SuggestionsBuilder
import com.mojang.brigadier.suggestion.Suggestions
import com.mojang.serialization.DataResult
import net.minecraft.commands.SharedSuggestionProvider
import net.minecraft.core.registries.BuiltInRegistries
import com.mojang.brigadier.exceptions.DynamicCommandExceptionType
import com.mojang.brigadier.exceptions.Dynamic2CommandExceptionType
import com.mojang.brigadier.exceptions.SimpleCommandExceptionType
import net.minecraft.core.component.DataComponentMap
import net.minecraft.core.component.PatchedDataComponentMap
import net.minecraftforge.common.data.ForgeAdvancementProvider.AdvancementGenerator
import net.minecraft.advancements.AdvancementHolder
import net.minecraftforge.common.data.ExistingFileHelper
import net.minecraft.advancements.Advancement
import net.minecraft.advancements.AdvancementType
import net.minecraft.advancements.critereon.InventoryChangeTrigger
import net.Chidoziealways.everythingjapanese.item.custom.Drinks
import net.minecraft.world.item.alchemy.PotionContents
import net.minecraft.core.component.DataComponents
import net.minecraft.world.item.alchemy.Potions
import net.minecraft.server.level.ServerPlayer
import net.minecraft.advancements.CriteriaTriggers
import net.minecraft.world.effect.MobEffectInstance
import net.minecraft.world.level.gameevent.GameEvent
import net.minecraft.world.item.context.UseOnContext
import net.minecraft.world.InteractionResult
import net.minecraft.world.level.block.state.BlockState
import net.minecraft.tags.BlockTags
import net.minecraft.sounds.SoundSource
import net.minecraft.world.item.ItemUtils
import net.minecraft.core.particles.SimpleParticleType
import net.minecraft.core.particles.ParticleTypes
import net.minecraft.world.item.ItemUseAnimation
import net.minecraft.world.InteractionHand
import net.minecraft.data.tags.IntrinsicHolderTagsProvider
import net.Chidoziealways.everythingjapanese.util.ModTags
import net.minecraft.data.tags.KeyTagProvider
import net.minecraft.world.level.biome.Biome
import net.Chidoziealways.everythingjapanese.worldgen.biome.ModBiomes
import net.minecraft.server.level.ServerBossEvent
import net.minecraft.world.BossEvent
import net.Chidoziealways.everythingjapanese.entity.custom.TriceratopsEntity
import net.Chidoziealways.everythingjapanese.entity.TriceratopsVariant
import net.minecraft.world.level.ServerLevelAccessor
import net.minecraft.world.DifficultyInstance
import net.minecraft.world.entity.SpawnGroupData
import net.minecraft.network.syncher.EntityDataSerializers
import net.minecraft.world.item.ProjectileItem
import net.minecraft.world.entity.projectile.AbstractArrow
import net.Chidoziealways.everythingjapanese.entity.custom.YaProjectileEntity
import net.minecraft.world.entity.projectile.Projectile
import net.Chidoziealways.everythingjapanese.jutsu.IJutsuCapability
import net.minecraft.world.item.enchantment.Enchantment
import net.minecraft.data.worldgen.BootstrapContext
import net.minecraft.core.HolderGetter
import net.Chidoziealways.everythingjapanese.enchantment.ModEnchantments
import net.minecraft.tags.ItemTags
import net.minecraft.world.entity.EquipmentSlotGroup
import net.minecraft.tags.EnchantmentTags
import net.minecraft.world.item.enchantment.effects.EnchantmentEntityEffect
import net.minecraft.world.item.enchantment.EnchantmentEffectComponents
import net.minecraft.world.item.enchantment.EnchantmentTarget
import net.Chidoziealways.everythingjapanese.enchantment.custom.LightningStrikerEnchantmentEffect
import net.minecraft.world.food.FoodProperties
import net.minecraft.world.item.component.Consumable
import net.minecraft.world.item.component.Consumables
import net.minecraft.world.item.consume_effects.ApplyStatusEffectsConsumeEffect
import net.minecraft.world.effect.MobEffects
import net.minecraft.world.item.equipment.ArmorMaterial
import net.minecraft.world.item.equipment.ArmorType
import net.minecraft.client.renderer.entity.EntityRendererProvider
import net.minecraft.client.renderer.entity.MobRenderer
import net.Chidoziealways.everythingjapanese.entity.custom.SikaDeerEntity
import net.Chidoziealways.everythingjapanese.entity.client.sikadeer.SikaDeerRenderState
import net.Chidoziealways.everythingjapanese.entity.client.sikadeer.SikaDeerModel
import net.Chidoziealways.everythingjapanese.entity.client.ModModelLayers
import net.minecraft.client.model.AdultAndBabyModelPair
import net.Chidoziealways.everythingjapanese.entity.client.sikadeer.SikaDeerRenderer
import com.mojang.serialization.codecs.RecordCodecBuilder
import java.util.function.BiFunction
import net.minecraft.world.phys.BlockHitResult
import net.Chidoziealways.everythingjapanese.portal.HellPortalShape
import net.minecraftforge.event.TickEvent.ServerTickEvent
import net.Chidoziealways.everythingjapanese.network.ModNetwork
import net.Chidoziealways.everythingjapanese.chakra.ChakraSyncPacket
import net.minecraftforge.network.PacketDistributor
import net.minecraft.world.item.enchantment.EnchantedItemInUse
import com.mojang.serialization.MapCodec
import net.minecraft.world.item.CreativeModeTab
import net.Chidoziealways.everythingjapanese.item.ModCreativeModeTabs
import net.minecraft.world.item.CreativeModeTab.DisplayItemsGenerator
import net.minecraft.world.item.CreativeModeTab.ItemDisplayParameters
import net.Chidoziealways.everythingjapanese.EverythingJapanese
import net.minecraftforge.common.data.ForgeAdvancementProvider
import net.Chidoziealways.everythingjapanese.datagen.HellAdvancementProvider
import net.Chidoziealways.everythingjapanese.datagen.StoryAdvancementProvider
import net.minecraft.world.level.ClipContext
import net.minecraft.world.phys.HitResult
import net.minecraftforge.event.level.BlockEvent.BreakEvent
import net.Chidoziealways.everythingjapanese.item.custom.HammerItem
import net.Chidoziealways.everythingjapanese.event.ModEvents
import net.minecraftforge.event.entity.player.PlayerInteractEvent.EntityInteract
import net.minecraftforge.event.entity.living.LivingDamageEvent
import net.minecraftforge.event.entity.living.LivingHurtEvent
import net.Chidoziealways.everythingjapanese.effect.ModEffects
import net.minecraftforge.event.brewing.BrewingRecipeRegisterEvent
import net.minecraft.world.item.alchemy.PotionBrewing
import net.Chidoziealways.everythingjapanese.potion.ModPotions
import net.minecraftforge.event.village.VillagerTradesEvent
import net.minecraft.world.entity.npc.VillagerProfession
import net.minecraft.world.entity.npc.VillagerTrades.ItemListing
import net.minecraft.util.RandomSource
import net.minecraft.world.item.trading.MerchantOffer
import net.minecraft.world.item.trading.ItemCost
import net.Chidoziealways.everythingjapanese.villager.ModVillagers
import net.minecraftforge.event.village.WandererTradesEvent
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState
import net.minecraft.client.renderer.entity.EntityRenderer
import net.Chidoziealways.everythingjapanese.entity.client.ya.YaRenderState
import net.minecraft.util.Mth
import com.mojang.blaze3d.vertex.VertexConsumer
import net.minecraft.world.item.crafting.RecipeType
import net.minecraft.world.level.block.entity.BlockEntityType
import net.minecraftforge.registries.ForgeRegistries
import net.Chidoziealways.everythingjapanese.entity.ModBlockEntities
import net.minecraft.world.level.block.entity.BlockEntityType.BlockEntitySupplier
import net.minecraft.client.model.geom.ModelLayerLocation
import net.minecraft.world.phys.Vec2
import net.minecraft.world.phys.EntityHitResult
import net.minecraft.client.animation.AnimationDefinition
import net.minecraft.client.animation.AnimationChannel
import net.minecraft.client.animation.KeyframeAnimations
import net.Chidoziealways.everythingjapanese.entity.custom.ChairEntity
import net.Chidoziealways.everythingjapanese.entity.client.chair.ChairRenderState
import net.minecraft.client.renderer.culling.Frustum
import net.minecraft.client.model.geom.ModelPart
import net.minecraft.client.model.EntityModel
import net.minecraft.client.animation.KeyframeAnimation
import net.Chidoziealways.everythingjapanese.entity.client.sikadeer.SikaDeerAnimations
import net.minecraft.client.model.geom.builders.MeshTransformer
import net.minecraft.client.model.BabyModelTransform
import net.minecraft.client.model.geom.builders.LayerDefinition
import net.minecraft.client.model.geom.builders.MeshDefinition
import net.minecraft.client.model.geom.builders.PartDefinition
import net.minecraft.client.model.geom.builders.CubeListBuilder
import net.minecraft.client.model.geom.PartPose
import net.minecraft.client.model.geom.builders.CubeDeformation
import net.Chidoziealways.everythingjapanese.entity.custom.IronBattleAxeProjectileEntity
import net.Chidoziealways.everythingjapanese.entity.client.ironbattleaxe.IronBattleAxeRenderState
import net.Chidoziealways.everythingjapanese.entity.client.ironbattleaxe.IronBattleAxeProjectileModel
import net.minecraft.network.FriendlyByteBuf
import net.minecraftforge.event.network.CustomPayloadEvent
import net.Chidoziealways.everythingjapanese.enchantment.ModEnchantmentEffects
import net.minecraft.client.gui.GuiGraphics
import net.minecraftforge.client.event.ComputeFovModifierEvent
import net.minecraft.world.item.Item.TooltipContext
import net.minecraft.world.item.component.TooltipDisplay
import net.minecraft.world.item.TooltipFlag
import java.util.function.ToIntFunction
import net.minecraftforge.registries.NewRegistryEvent
import net.Chidoziealways.everythingjapanese.event.ModRegistryEvents
import net.minecraftforge.common.data.GlobalLootModifierProvider
import net.Chidoziealways.everythingjapanese.loot.AddItemModifier
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition
import net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition
import net.minecraft.world.level.storage.loot.predicates.LootItemRandomChanceCondition
import net.minecraftforge.common.loot.LootTableIdCondition
import net.minecraftforge.common.capabilities.AutoRegisterCapability
import net.minecraft.data.loot.BlockLootSubProvider
import net.minecraft.advancements.critereon.StatePropertiesPredicate
import net.minecraft.world.level.storage.loot.LootTable
import net.minecraft.world.level.storage.loot.LootPool
import net.minecraft.world.level.block.SweetBerryBushBlock
import net.minecraft.world.level.storage.loot.entries.LootItem
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator
import net.minecraft.world.level.storage.loot.functions.ApplyBonusCount
import net.Chidoziealways.everythingjapanese.effect.AdrenalineEffect
import net.minecraft.world.entity.ai.attributes.AttributeModifier
import com.mojang.brigadier.arguments.IntegerArgumentType
import net.Chidoziealways.everythingjapanese.commands.comands.SetChakraCommand
import net.minecraft.client.renderer.entity.state.EntityRenderState
import net.minecraft.data.recipes.RecipeOutput
import net.minecraft.data.recipes.RecipeProvider
import net.minecraftforge.common.crafting.conditions.IConditionBuilder
import net.Chidoziealways.everythingjapanese.datagen.ModRecipeProvider
import net.minecraft.world.item.equipment.trim.TrimPattern
import net.minecraft.world.item.crafting.Recipe
import net.minecraft.world.level.ItemLike
import net.minecraft.data.recipes.RecipeCategory
import net.minecraft.world.item.crafting.Ingredient
import net.minecraft.world.item.crafting.SmeltingRecipe
import net.minecraft.world.item.crafting.RecipeSerializer
import net.minecraft.world.item.crafting.AbstractCookingRecipe
import net.minecraft.world.item.crafting.CookingBookCategory
import net.minecraft.world.item.crafting.SmokingRecipe
import net.minecraft.world.item.crafting.BlastingRecipe
import net.minecraft.data.recipes.SimpleCookingRecipeBuilder
import net.minecraft.data.recipes.ShapedRecipeBuilder
import net.minecraft.data.recipes.ShapelessRecipeBuilder
import net.Chidoziealways.everythingjapanese.trim.ModTrimPatterns
import net.minecraft.core.particles.ColorParticleOption
import net.minecraftforge.common.capabilities.CapabilityManager
import net.minecraftforge.common.capabilities.CapabilityToken
import net.minecraftforge.client.event.EntityRenderersEvent.RegisterLayerDefinitions
import net.Chidoziealways.everythingjapanese.entity.client.triceratops.TriceratopsModel
import net.minecraftforge.event.entity.EntityAttributeCreationEvent
import net.minecraftforge.event.entity.SpawnPlacementRegisterEvent
import net.minecraft.world.entity.SpawnPlacementTypes
import net.minecraft.world.level.levelgen.Heightmap
import net.minecraft.world.entity.SpawnPlacements
import net.minecraft.advancements.critereon.ChangeDimensionTrigger
import net.Chidoziealways.everythingjapanese.worldgen.dimension.ModDimensions
import net.minecraft.advancements.AdvancementRewards
import net.minecraft.advancements.critereon.PlayerTrigger
import net.minecraft.advancements.critereon.LocationPredicate
import net.Chidoziealways.everythingjapanese.structure.ModStructures
import net.minecraft.world.item.equipment.EquipmentAssets
import net.Chidoziealways.everythingjapanese.datagen.ModItemTagProvider
import net.Chidoziealways.everythingjapanese.entity.client.triceratops.TriceratopsRenderState
import net.Chidoziealways.everythingjapanese.entity.client.triceratops.TriceratopsAnimations
import net.minecraftforge.data.event.GatherDataEvent
import net.minecraft.data.DataGenerator
import net.Chidoziealways.everythingjapanese.datagen.ModDatapackEntries
import net.minecraft.data.loot.LootTableProvider
import net.minecraft.data.loot.LootTableProvider.SubProviderEntry
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets
import net.Chidoziealways.everythingjapanese.datagen.ModBlockTagProvider
import net.Chidoziealways.everythingjapanese.datagen.ModBiomeTagProvider
import net.Chidoziealways.everythingjapanese.datagen.ModModelProvider
import net.Chidoziealways.everythingjapanese.datagen.ModGlobalLootModifierProvider
import net.Chidoziealways.everythingjapanese.datagen.ModAdvancementProvider
import net.Chidoziealways.everythingjapanese.jutsu.ModJutsus
import net.Chidoziealways.everythingjapanese.commands.argumentTypes.jutsu.JutsuInput
import com.mojang.serialization.DynamicOps
import net.minecraft.core.component.TypedDataComponent
import net.minecraftforge.common.data.DatapackBuiltinEntriesProvider
import net.minecraft.core.RegistrySetBuilder
import net.minecraft.world.level.dimension.DimensionType
import net.minecraft.data.worldgen.DimensionTypes
import net.minecraft.world.level.levelgen.carver.ConfiguredWorldCarver
import net.minecraft.data.worldgen.Carvers
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature
import net.minecraft.data.worldgen.features.FeatureUtils
import net.minecraft.world.level.levelgen.placement.PlacedFeature
import net.minecraft.data.worldgen.placement.PlacementUtils
import net.minecraft.data.worldgen.StructureSets
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessorList
import net.minecraft.data.worldgen.ProcessorLists
import net.minecraft.world.level.levelgen.structure.pools.StructureTemplatePool
import net.minecraft.data.worldgen.Pools
import net.minecraft.data.worldgen.biome.BiomeData
import net.minecraft.world.level.biome.MultiNoiseBiomeSourceParameterList
import net.minecraft.world.level.biome.MultiNoiseBiomeSourceParameterLists
import net.minecraft.world.level.levelgen.synth.NormalNoise.NoiseParameters
import net.minecraft.data.worldgen.NoiseData
import net.minecraft.world.level.levelgen.DensityFunction
import net.minecraft.world.level.levelgen.NoiseRouterData
import net.minecraft.world.level.levelgen.NoiseGeneratorSettings
import net.minecraft.world.level.levelgen.presets.WorldPreset
import net.minecraft.world.level.levelgen.presets.WorldPresets
import net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorPreset
import net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorPresets
import net.minecraft.network.chat.ChatType
import net.minecraft.world.item.equipment.trim.TrimPatterns
import net.minecraft.world.level.block.entity.trialspawner.TrialSpawnerConfig
import net.minecraft.world.level.block.entity.trialspawner.TrialSpawnerConfigs
import net.minecraft.world.entity.animal.wolf.WolfVariant
import net.minecraft.world.entity.animal.wolf.WolfVariants
import net.minecraft.world.entity.animal.wolf.WolfSoundVariant
import net.minecraft.world.entity.animal.wolf.WolfSoundVariants
import net.minecraft.world.entity.decoration.PaintingVariant
import net.minecraft.world.entity.decoration.PaintingVariants
import net.minecraft.world.damagesource.DamageType
import net.minecraft.world.damagesource.DamageTypes
import net.minecraft.world.level.block.entity.BannerPattern
import net.minecraft.world.level.block.entity.BannerPatterns
import net.minecraft.world.item.enchantment.providers.EnchantmentProvider
import net.minecraft.world.item.enchantment.providers.VanillaEnchantmentProviders
import net.minecraft.world.item.JukeboxSong
import net.minecraft.world.item.JukeboxSongs
import net.minecraft.world.item.Instruments
import net.minecraft.world.entity.animal.PigVariant
import net.minecraft.world.entity.animal.PigVariants
import net.minecraft.world.entity.animal.CowVariant
import net.minecraft.world.entity.animal.CowVariants
import net.minecraft.world.entity.animal.ChickenVariant
import net.minecraft.world.entity.animal.ChickenVariants
import net.minecraft.gametest.framework.TestEnvironmentDefinition
import net.minecraft.gametest.framework.GameTestEnvironments
import net.minecraft.gametest.framework.GameTestInstance
import net.minecraft.gametest.framework.GameTestInstances
import net.minecraft.world.entity.animal.frog.FrogVariant
import net.minecraft.world.entity.animal.frog.FrogVariants
import net.minecraft.world.entity.animal.CatVariant
import net.minecraft.world.entity.animal.CatVariants
import net.minecraft.world.level.dimension.LevelStem
import net.Chidoziealways.everythingjapanese.worldgen.ModConfiguredFeatures
import net.Chidoziealways.everythingjapanese.worldgen.ModPlacedFeatures
import net.Chidoziealways.everythingjapanese.structure.ModStructuresGen
import net.Chidoziealways.everythingjapanese.structure.ModStructureSets
import net.Chidoziealways.everythingjapanese.structure.ModProcessorLists
import net.Chidoziealways.everythingjapanese.structure.ModPools
import net.minecraftforge.common.world.BiomeModifier
import net.Chidoziealways.everythingjapanese.worldgen.ModBiomeModifiers
import net.Chidoziealways.everythingjapanese.tests.environments.ModGameTestEnvironments
import net.Chidoziealways.everythingjapanese.tests.instances.ModGameTestInstances
import net.minecraft.core.HolderSet
import net.minecraft.world.level.levelgen.placement.BiomeFilter
import net.minecraft.core.RegistryAccess.Frozen
import net.minecraft.core.RegistryAccess
import net.Chidoziealways.everythingjapanese.entity.client.triceratops.TriceratopsRenderer
import net.minecraft.world.level.block.state.BlockBehaviour
import net.minecraft.world.level.block.DropExperienceBlock
import net.minecraft.util.valueproviders.UniformInt
import net.Chidoziealways.everythingjapanese.sound.ModSounds
import net.minecraft.world.level.material.PushReaction
import net.minecraft.world.level.block.CakeBlock
import net.minecraft.world.level.block.RotatedPillarBlock
import net.minecraft.world.level.BlockGetter
import net.minecraft.world.level.block.TintedParticleLeavesBlock
import net.minecraft.world.level.block.SaplingBlock
import net.Chidoziealways.everythingjapanese.worldgen.tree.ModTreeGrowers
import net.minecraft.world.level.block.FlowerPotBlock
import net.minecraft.world.level.block.StairBlock
import net.minecraft.world.level.block.SlabBlock
import net.minecraft.world.level.block.PressurePlateBlock
import net.minecraft.world.level.block.state.properties.BlockSetType
import net.minecraft.world.level.block.ButtonBlock
import net.minecraft.world.level.block.FenceBlock
import net.minecraft.world.level.block.FenceGateBlock
import net.minecraft.world.level.block.state.properties.WoodType
import net.minecraft.world.level.block.WallBlock
import net.minecraft.world.level.block.DoorBlock
import net.minecraft.world.level.block.TrapDoorBlock
import net.minecraft.world.item.BlockItem
import net.minecraft.world.entity.EntityType.EntityFactory
import net.minecraft.world.entity.MobCategory
import org.apache.logging.log4j.MarkerManager
import net.Chidoziealways.everythingjapanese.item.custom.ChiselItem
import net.minecraft.world.entity.EquipmentSlot
import net.minecraft.core.particles.BlockParticleOption
import net.Chidoziealways.everythingjapanese.particle.ModParticles
import net.Chidoziealways.everythingjapanese.component.ModDataComponentTypes
import net.minecraft.world.item.component.BlockItemStateProperties
import net.Chidoziealways.everythingjapanese.capabilities.PlayerEvents
import net.minecraftforge.event.entity.living.LivingDeathEvent
import net.minecraftforge.event.entity.player.PlayerEvent.PlayerLoggedOutEvent
import net.minecraftforge.event.entity.player.PlayerEvent.PlayerLoggedInEvent
import net.minecraftforge.event.entity.player.PlayerEvent.PlayerChangedDimensionEvent
import net.minecraftforge.event.entity.player.PlayerEvent
import net.minecraftforge.event.AttachCapabilitiesEvent
import net.Chidoziealways.everythingjapanese.jutsu.JutsuProvider
import java.util.function.UnaryOperator
import net.minecraft.world.item.ToolMaterial
import net.Chidoziealways.everythingjapanese.item.custom.JutsuScrollItem
import net.Chidoziealways.everythingjapanese.item.custom.HellPortalItem
import net.Chidoziealways.everythingjapanese.item.ModToolMaterials
import net.minecraft.world.item.component.BlocksAttacks
import net.minecraft.world.item.component.BlocksAttacks.DamageReduction
import net.minecraft.world.item.component.BlocksAttacks.ItemDamageFunction
import net.minecraft.tags.DamageTypeTags
import net.Chidoziealways.everythingjapanese.item.ModFoodProperties
import net.Chidoziealways.everythingjapanese.item.custom.FuelItem
import net.minecraft.world.item.ArrowItem
import net.Chidoziealways.everythingjapanese.item.custom.Katana
import net.Chidoziealways.everythingjapanese.item.ModArmorMaterials
import net.minecraft.world.item.SmithingTemplateItem
import net.minecraft.world.item.Rarity
import net.minecraft.world.item.BowItem
import net.minecraft.world.item.SpawnEggItem
import net.minecraft.world.item.MaceItem
import net.Chidoziealways.everythingjapanese.item.custom.IronBattleAxeItem
import net.minecraftforge.event.entity.player.ItemTooltipEvent
import net.Chidoziealways.everythingjapanese.jutsu.JutsuType
import net.minecraft.world.entity.projectile.LargeFireball
import net.minecraft.world.entity.projectile.SmallFireball
import net.minecraft.world.entity.projectile.windcharge.WindCharge
import net.Chidoziealways.everythingjapanese.jutsu.CycleJutsuPacket
import net.Chidoziealways.everythingjapanese.jutsu.JutsuCapability
import net.Chidoziealways.everythingjapanese.jutsu.JutsuCastPacket
import net.minecraftforge.common.loot.LootModifier
import net.minecraft.world.level.storage.loot.LootContext
import net.minecraftforge.common.loot.IGlobalLootModifier
import net.Chidoziealways.everythingjapanese.loot.ModLootModifiers
*/