---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/21/2025 12:20 PM
---

--local Globals = require("globals")

return function(level, pos, player)
    local dir = player:getDirection()

    print("Running Fire Function")

    if dir == nil then
        print("⚠️ Player direction is nil! Skipping fire effect.")
        return
    else
        print("Direction is not nil!")
    end

    local baseBlock = pos:relative(dir)
    print("Gotten BaseBlock Pos")
    local above = baseBlock:above()
    print("Gotten AboveBlock Pos")
    local fireBlock = getBlock("minecraft:fire")
    print("Gotten FireBlock")
    if level:isEmptyBlock(above) then
        print("Checking if EmptyBlock")
        level:setBlock(above, fireBlock:defaultBlockState(), 11)
        print("Empty Block!")
    else
        print("Not An Empty Block!")
    end
end
