---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/22/2025 9:59 AM
---

return function(level, pos, player)
    spawnEntity(level, pos, "minecraft:lightning_bolt")
end
