---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/22/2025 9:49 AM
---

return function(level, pos, player)
    local ModCapabilities = luajava.bindClass("net.Chidoziealways.everythingjapanese.capabilities.ModCapabilities")
    print(ModCapabilities)
    print(ModCapabilities.LOCK_CAPABILITY)
    local lock = getBlockLock(level, pos)
    if lock == nil then return end
    lock:setLocked(true)
    lock:setOwner(player:getUUID())
    displayClientMessage(player, literalComponent("Sealed Block! Owner is " ..player:getStringUUID()), true)
end