---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/22/2025 9:47 AM
---

return function(level, pos, player)
    local dir = player:getDirection()

    print("Running Fire Function")

    if dir == nil then
        print("⚠️ Player direction is nil! Skipping fire effect.")
        return
    else
        print("Direction is not nil!")
    end

    local baseBlock = pos:relative(dir)
    print("Gotten BaseBlock Pos")
    local above = baseBlock:above()
    print("Gotten AboveBlock Pos")
    local waterBlock = getBlock("minecraft:water")
    print("Gotten FireBlock")
    if level:isEmptyBlock(above) then
        print("Checking if EmptyBlock")
        level:setBlock(above, waterBlock:defaultBlockState(), 11)
        print("Empty Block!")
    else
        print("Not An Empty Block!")
    end
end