---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 2:29 PM
---

return function(player, level)
    for i = 1, 65 do
        local iron = getItem("minecraft:iron"):getDefaultInstance()
        player.getInventory():add(iron)
    end
end