---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 3:01 PM
---

return function(player, level)
    local gun = getItem("everythingjapanese:gun"):getDefaultInstance()
    player.getInventory():add(gun)

    for i = 1, 65 do
        local bullet = getItem("everythingjapanese:bullet"):getDefaultInstance()
        player.getInventory():add(bullet)
    end
end