---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 2:47 PM
---

return function(player, quest, stage)
    return isInsideStructure(player, "everythingjapanese:dojo")
end