---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/22/2025 12:42 PM
---

return function(level, pos, player, target)
    spawnEntity(level, target:blockPosition(), "minecraft:lightning_bolt")
end