---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/22/2025 12:43 PM
---

return function(level, pos, player, target)
    print("Don't think you can 'seal' entities")
end