---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/22/2025 12:40 PM
---

return function(level, pos, player, target)
    local serverLevel = level  -- assume this is a ServerLevel
    local damageSource = player:damageSources():drown()
    target:hurtServer(serverLevel, damageSource, 4.0)
end