import net.Chidoziealways.everythingjapanese.chakra.ChakraHUDOverlay.renderChakraBar
import net.minecraft.client.gui.Gui
import org.spongepowered.asm.mixin.Shadow
import org.spongepowered.asm.mixin.Final
import net.minecraft.client.Minecraft
import net.minecraft.client.gui.GuiGraphics
import net.minecraft.client.DeltaTracker
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo
import net.Chidoziealways.everythingjapanese.chakra.IChakra
import net.Chidoziealways.everythingjapanese.capabilities.ModCapabilities
import net.minecraftforge.common.util.NonNullConsumer
import net.Chidoziealways.everythingjapanese.chakra.ChakraHUDOverlay
import net.Chidoziealways.everythingjapanese.mixins.GuiMixin
import net.minecraftforge.network.SimpleChannel
import net.minecraftforge.network.ChannelBuilder
import net.minecraftforge.network.Channel.VersionTest
import net.Chidoziealways.everythingjapanese.network.ModNetwork
import net.Chidoziealways.everythingjapanese.chakra.ChakraSyncPacket
import net.minecraft.network.RegistryFriendlyByteBuf
import net.minecraftforge.network.NetworkDirection
import net.minecraftforge.event.network.CustomPayloadEvent
import net.Chidoziealways.everythingjapanese.jutsu.JutsuCastPacket
import net.Chidoziealways.everythingjapanese.jutsu.CycleJutsuPacket
import net.minecraftforge.registries.DeferredRegister
import net.minecraft.core.particles.ParticleType
import net.minecraftforge.registries.ForgeRegistries
import net.minecraftforge.registries.RegistryObject
import net.minecraft.core.particles.SimpleParticleType
import net.Chidoziealways.everythingjapanese.particle.ModParticles
import net.minecraftforge.eventbus.api.bus.BusGroup
import net.minecraft.client.multiplayer.ClientLevel
import net.minecraft.client.particle.SpriteSet
import net.minecraft.client.particle.TextureSheetParticle
import net.minecraft.client.particle.ParticleRenderType
import net.minecraft.client.particle.ParticleProvider
import net.Chidoziealways.everythingjapanese.particle.PyriteParticles
import net.minecraft.world.entity.ai.village.poi.PoiType
import net.Chidoziealways.everythingjapanese.poi.ModPoiTypes
import net.minecraft.world.level.block.state.BlockState
import net.Chidoziealways.everythingjapanese.block.ModBlocks
import net.minecraft.server.level.ServerLevel
import net.minecraft.core.BlockPos
import net.minecraft.world.level.border.WorldBorder
import net.minecraft.world.entity.ai.village.poi.PoiManager
import net.minecraft.world.entity.ai.village.poi.PoiRecord
import net.minecraft.world.level.block.state.properties.BlockStateProperties
import java.util.function.ToIntFunction
import net.minecraft.BlockUtil.FoundRectangle
import net.minecraft.core.BlockPos.MutableBlockPos
import net.minecraft.world.level.levelgen.Heightmap
import net.minecraft.util.Mth
import net.minecraft.world.level.LevelAccessor
import net.minecraft.world.level.block.NetherPortalBlock
import net.minecraft.world.level.block.state.BlockBehaviour.StatePredicate
import net.minecraft.world.level.BlockGetter
import net.Chidoziealways.everythingjapanese.portal.HellPortalShape
import net.minecraft.tags.BlockTags
import net.minecraft.world.phys.Vec3
import net.minecraft.world.entity.EntityDimensions
import net.minecraft.world.phys.shapes.VoxelShape
import net.minecraft.world.phys.shapes.Shapes
import net.minecraft.world.phys.AABB
import net.Chidoziealways.everythingjapanese.potion.ModPotions
import net.minecraft.world.effect.MobEffectInstance
import net.Chidoziealways.everythingjapanese.effect.ModEffects
import net.minecraft.util.StringRepresentable
import net.Chidoziealways.everythingjapanese.recipe.GrowthChamberCategory
import java.util.function.IntFunction
import net.minecraft.util.ByIdMap
import net.minecraft.network.codec.StreamCodec
import io.netty.buffer.ByteBuf
import net.minecraft.network.codec.ByteBufCodecs
import net.minecraft.world.item.crafting.Ingredient
import net.minecraft.world.item.ItemStack
import net.minecraft.world.item.crafting.Recipe
import net.Chidoziealways.everythingjapanese.recipe.GrowthChamberRecipeInput
import net.minecraft.core.HolderLookup
import net.minecraft.world.item.crafting.RecipeSerializer
import net.Chidoziealways.everythingjapanese.recipe.ModRecipes
import net.minecraft.world.item.crafting.RecipeType
import net.minecraft.world.item.crafting.PlacementInfo
import net.Chidoziealways.everythingjapanese.recipe.GrowthChamberRecipe
import net.minecraft.world.item.crafting.RecipeBookCategory
import net.minecraft.world.item.crafting.RecipeBookCategories
import com.mojang.serialization.MapCodec
import com.mojang.serialization.codecs.RecordCodecBuilder
import net.minecraft.world.item.crafting.RecipeInput
import net.Chidoziealways.everythingjapanese.recipe.ModRecipeBookCategories
import net.minecraft.world.entity.player.Inventory
import net.minecraft.world.level.block.entity.BlockEntity
import net.minecraft.world.inventory.ContainerData
import net.minecraft.world.inventory.AbstractContainerMenu
import net.Chidoziealways.everythingjapanese.screen.ModMenuTypes
import net.minecraft.network.FriendlyByteBuf
import net.minecraft.world.inventory.SimpleContainerData
import net.minecraftforge.items.SlotItemHandler
import net.Chidoziealways.everythingjapanese.screen.custom.growthchamber.GrowthChamberMenu
import net.minecraft.world.inventory.ContainerLevelAccess
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen
import net.Chidoziealways.everythingjapanese.screen.custom.growthchamber.GrowthChamberScreen
import net.Chidoziealways.everythingjapanese.screen.custom.pedestal.PedestalMenu
import net.Chidoziealways.everythingjapanese.screen.custom.pedestal.PedestalScreen
import net.minecraft.world.inventory.MenuType
import net.minecraftforge.common.extensions.IForgeMenuType
import net.minecraftforge.network.IContainerFactory
import net.Chidoziealways.everythingjapanese.sound.ModSounds
import net.minecraftforge.common.util.ForgeSoundType
import net.minecraft.resources.ResourceKey
import net.minecraft.world.item.JukeboxSong
import net.minecraft.world.level.levelgen.structure.pools.StructureTemplatePool
import net.minecraft.data.worldgen.Pools
import net.minecraft.data.worldgen.BootstrapContext
import net.minecraft.core.HolderGetter
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessorList
import net.Chidoziealways.everythingjapanese.structure.ModProcessorLists
import net.Chidoziealways.everythingjapanese.structure.custom.hellTemple.HellTempleStructurePieces
import net.minecraft.world.level.levelgen.structure.pools.StructurePoolElement
import net.Chidoziealways.everythingjapanese.structure.custom.hellTemple.HellTempleStructurePools
import net.Chidoziealways.everythingjapanese.structure.ModPools
import net.Chidoziealways.everythingjapanese.EverythingJapanese
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessor
import net.minecraft.world.level.levelgen.structure.templatesystem.ProcessorRule
import net.minecraft.world.level.levelgen.structure.templatesystem.RandomBlockMatchTest
import net.minecraft.world.level.levelgen.structure.templatesystem.AlwaysTrueTest
import net.minecraft.world.level.levelgen.structure.templatesystem.RuleProcessor
import net.minecraft.world.level.levelgen.structure.templatesystem.ProtectedBlockProcessor
import net.Chidoziealways.everythingjapanese.structure.ModStructures
import net.Chidoziealways.everythingjapanese.structure.ModStructureSets
import net.minecraft.world.level.biome.Biome
import net.minecraft.world.level.levelgen.structure.placement.RandomSpreadStructurePlacement
import net.minecraft.world.level.levelgen.structure.placement.RandomSpreadType
import net.Chidoziealways.everythingjapanese.structure.ModStructuresGen
import net.minecraft.world.level.levelgen.structure.structures.JigsawStructure
import net.minecraft.world.level.levelgen.structure.Structure.StructureSettings
import net.minecraft.world.entity.MobCategory
import net.minecraft.world.level.levelgen.structure.StructureSpawnOverride
import net.minecraft.world.level.levelgen.structure.structures.NetherFortressStructure
import net.minecraft.world.level.levelgen.GenerationStep
import net.minecraft.world.level.levelgen.heightproviders.ConstantHeight
import net.minecraft.world.level.levelgen.VerticalAnchor
import net.minecraft.world.level.levelgen.structure.pools.alias.PoolAliasBinding
import net.minecraft.world.level.levelgen.structure.StructureType
import net.minecraft.world.level.levelgen.structure.pieces.StructurePieceType
import net.minecraft.world.level.levelgen.structure.pieces.StructurePieceType.ContextlessType
import net.Chidoziealways.everythingjapanese.structure.ModStructuresR
import net.minecraft.gametest.framework.TestEnvironmentDefinition
import net.Chidoziealways.everythingjapanese.tests.environments.ModGameTestEnvironments
import net.minecraft.gametest.framework.TestEnvironmentDefinition.Weather
import net.minecraft.gametest.framework.GameTestInstance
import net.Chidoziealways.everythingjapanese.tests.instances.ModGameTestInstances
import net.minecraft.gametest.framework.GameTestHelper
import net.minecraft.gametest.framework.FunctionGameTestInstance
import net.Chidoziealways.everythingjapanese.tests.ModGameTests
import net.minecraft.gametest.framework.TestData
import net.minecraft.world.item.equipment.trim.MaterialAssetGroup
import net.minecraft.world.item.equipment.trim.TrimMaterial
import net.Chidoziealways.everythingjapanese.trim.ModTrimMaterials
import net.minecraft.network.chat.TextColor
import net.Chidoziealways.everythingjapanese.trim.ModMaterialAssetGroup
import net.minecraft.world.item.equipment.trim.TrimPattern
import net.Chidoziealways.everythingjapanese.trim.ModTrimPatterns
import net.minecraftforge.fml.common.Mod.EventBusSubscriber
import net.minecraftforge.api.distmarker.Dist
import net.minecraftforge.eventbus.api.listener.SubscribeEvent
import net.Chidoziealways.everythingjapanese.util.ModKeyBinds
import org.lwjgl.glfw.GLFW
import net.minecraftforge.network.PacketDistributor
import net.minecraft.client.KeyMapping
import net.minecraftforge.client.event.RegisterKeyMappingsEvent
import com.mojang.blaze3d.platform.InputConstants
import net.Chidoziealways.everythingjapanese.jutsu.Jutsu
import net.minecraft.world.entity.npc.VillagerProfession
import net.Chidoziealways.everythingjapanese.villager.ModVillagers
import net.Chidoziealways.everythingjapanese.worldgen.biome.ModBiomes
import net.minecraft.world.level.biome.BiomeGenerationSettings
import net.minecraft.data.worldgen.BiomeDefaultFeatures
import net.minecraft.world.level.biome.MobSpawnSettings
import net.minecraft.world.level.biome.MobSpawnSettings.SpawnerData
import net.minecraft.world.level.levelgen.placement.PlacedFeature
import net.minecraft.world.level.levelgen.carver.ConfiguredWorldCarver
import net.minecraft.world.level.biome.Biome.BiomeBuilder
import net.minecraft.world.level.biome.BiomeSpecialEffects
import net.minecraft.world.level.biome.AmbientMoodSettings
import net.minecraft.sounds.Musics
import net.minecraft.world.level.dimension.LevelStem
import net.minecraft.world.level.dimension.DimensionType
import net.Chidoziealways.everythingjapanese.worldgen.dimension.ModDimensions
import java.util.OptionalLong
import net.minecraft.world.level.dimension.BuiltinDimensionTypes
import net.minecraft.world.level.dimension.DimensionType.MonsterSettings
import net.minecraft.util.valueproviders.ConstantInt
import net.minecraft.world.level.levelgen.NoiseGeneratorSettings
import net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator
import net.minecraft.world.level.biome.FixedBiomeSource
import net.minecraft.world.level.biome.MultiNoiseBiomeSource
import net.minecraft.world.level.biome.Climate
import net.minecraft.world.level.biome.Climate.ParameterPoint
import net.minecraft.world.level.block.grower.TreeGrower
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature
import net.Chidoziealways.everythingjapanese.worldgen.ModConfiguredFeatures
import net.minecraftforge.common.world.BiomeModifier
import net.Chidoziealways.everythingjapanese.worldgen.ModBiomeModifiers
import net.minecraftforge.common.world.ForgeBiomeModifiers.AddFeaturesBiomeModifier
import net.minecraft.tags.BiomeTags
import net.minecraft.core.HolderSet
import net.Chidoziealways.everythingjapanese.worldgen.ModPlacedFeatures
import net.minecraftforge.common.world.ForgeBiomeModifiers.AddSpawnsBiomeModifier
import net.minecraft.util.random.WeightedList
import net.Chidoziealways.everythingjapanese.entity.ModEntities
import net.minecraft.world.level.levelgen.structure.templatesystem.RuleTest
import net.minecraft.world.level.levelgen.structure.templatesystem.TagMatchTest
import net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration.TargetBlockState
import net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration
import net.minecraft.world.level.levelgen.feature.configurations.TreeConfiguration
import net.minecraft.world.level.levelgen.feature.configurations.TreeConfiguration.TreeConfigurationBuilder
import net.minecraft.world.level.levelgen.feature.trunkplacers.DarkOakTrunkPlacer
import net.minecraft.world.level.levelgen.feature.foliageplacers.DarkOakFoliagePlacer
import net.minecraft.world.level.levelgen.feature.featuresize.ThreeLayersFeatureSize
import java.util.OptionalInt
import net.minecraft.world.level.levelgen.feature.configurations.RandomPatchConfiguration
import net.minecraft.data.worldgen.features.FeatureUtils
import net.minecraft.world.level.levelgen.feature.configurations.SimpleBlockConfiguration
import net.minecraft.world.level.levelgen.feature.configurations.FeatureConfiguration
import net.minecraft.world.level.levelgen.placement.PlacementModifier
import net.minecraft.world.level.levelgen.placement.InSquarePlacement
import net.minecraft.world.level.levelgen.placement.BiomeFilter
import net.Chidoziealways.everythingjapanese.worldgen.ModOrePlacement
import net.minecraft.world.level.levelgen.placement.CountPlacement
import net.minecraft.world.level.levelgen.placement.RarityFilter
import net.minecraft.world.level.levelgen.placement.HeightRangePlacement
import net.minecraft.data.worldgen.placement.VegetationPlacements
import net.minecraft.data.worldgen.placement.PlacementUtils
import net.minecraftforge.common.ForgeConfigSpec
import net.minecraftforge.fml.event.config.ModConfigEvent