---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 3:00 PM
---

return function(player, quest, stage)
    return isInsideStructure(player, "everythingjapanese:shoji_house")
end