---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 1:39 PM
---

return function(player, quest, stage)
    return isInsideStructure(player, "minecraft:village_plains")
end