---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 1:39 PM
---

print("FIND_VILLAGE INITIALIZED!!!")

return function(player, quest, stage)
    print("LOCATING VILLAGE")
    return true
end