---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 1:43 PM
---

return function(player, quest, stage)
    return hasCollectedItem(player, "minecraft:emerald")
end