---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 1:49 PM
---

return function(player, quest, stage)
    return hasKilledEntity(player, "minecraft:iron_golem")
end